In [2]:
data_science_jobs = [
    {'job_title': 'Data Scientist', 'job_skills': "['Python', 'SQL', 'Machine Learning']", 'job_date': '2023-05-12'},
    {'job_title': 'Machine Learning Engineer', 'job_skills': "['Python', 'TensorFlow', 'Deep Learning']", 'job_date': '2023-05-15'},
    {'job_title': 'Data Analyst', 'job_skills': "['SQL', 'R', 'Tableau']", 'job_date': '2023-05-10'},
    {'job_title': 'Business Intelligence Developer', 'job_skills': "['SQL', 'PowerBI', 'Data Warehousing']", 'job_date': '2023-05-08'},
    {'job_title': 'Data Engineer', 'job_skills': "['Python', 'Spark', 'Hadoop']", 'job_date': '2023-05-18'},
    {'job_title': 'AI Specialist', 'job_skills': "['Python', 'PyTorch', 'AI Ethics']", 'job_date': '2023-05-20'}
]

In [3]:
from datetime import datetime

test_date = data_science_jobs[0]['job_date']

print(test_date)
print(type(test_date))

2023-05-12
<class 'str'>


In [4]:
print(datetime.strptime(test_date, '%Y-%m-%d'))

2023-05-12 00:00:00


In [5]:
data_science_jobs = [
    {'job_title': 'Data Scientist', 'job_skills': "['Python', 'SQL', 'Machine Learning']", 'job_date': '2023-05-12'},
    {'job_title': 'Machine Learning Engineer', 'job_skills': "['Python', 'TensorFlow', 'Deep Learning']", 'job_date': '2023-05-15'},
    {'job_title': 'Data Analyst', 'job_skills': "['SQL', 'R', 'Tableau']", 'job_date': '2023-05-10'},
    {'job_title': 'Business Intelligence Developer', 'job_skills': "['SQL', 'PowerBI', 'Data Warehousing']", 'job_date': '2023-05-08'},
    {'job_title': 'Data Engineer', 'job_skills': "['Python', 'Spark', 'Hadoop']", 'job_date': '2023-05-18'},
    {'job_title': 'AI Specialist', 'job_skills': "['Python', 'PyTorch', 'AI Ethics']", 'job_date': '2023-05-20'}
]
from datetime import datetime

for job in data_science_jobs:
  job['job_date'] = datetime.strptime(job['job_date'], '%Y-%m-%d')

data_science_jobs

[{'job_title': 'Data Scientist',
  'job_skills': "['Python', 'SQL', 'Machine Learning']",
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Machine Learning Engineer',
  'job_skills': "['Python', 'TensorFlow', 'Deep Learning']",
  'job_date': datetime.datetime(2023, 5, 15, 0, 0)},
 {'job_title': 'Data Analyst',
  'job_skills': "['SQL', 'R', 'Tableau']",
  'job_date': datetime.datetime(2023, 5, 10, 0, 0)},
 {'job_title': 'Business Intelligence Developer',
  'job_skills': "['SQL', 'PowerBI', 'Data Warehousing']",
  'job_date': datetime.datetime(2023, 5, 8, 0, 0)},
 {'job_title': 'Data Engineer',
  'job_skills': "['Python', 'Spark', 'Hadoop']",
  'job_date': datetime.datetime(2023, 5, 18, 0, 0)},
 {'job_title': 'AI Specialist',
  'job_skills': "['Python', 'PyTorch', 'AI Ethics']",
  'job_date': datetime.datetime(2023, 5, 20, 0, 0)}]

In [7]:
#para converter skills em uma list

import ast

data_science_jobs = [
    {'job_title': 'Data Scientist', 'job_skills': "['Python', 'SQL', 'Machine Learning']", 'job_date': '2023-05-12'},
    {'job_title': 'Machine Learning Engineer', 'job_skills': "['Python', 'TensorFlow', 'Deep Learning']", 'job_date': '2023-05-15'},
    {'job_title': 'Data Analyst', 'job_skills': "['SQL', 'R', 'Tableau']", 'job_date': '2023-05-10'},
    {'job_title': 'Business Intelligence Developer', 'job_skills': "['SQL', 'PowerBI', 'Data Warehousing']", 'job_date': '2023-05-08'},
    {'job_title': 'Data Engineer', 'job_skills': "['Python', 'Spark', 'Hadoop']", 'job_date': '2023-05-18'},
    {'job_title': 'AI Specialist', 'job_skills': "['Python', 'PyTorch', 'AI Ethics']", 'job_date': '2023-05-20'}
]

import ast
from datetime import datetime

for job in data_science_jobs:
    job['job_date'] = datetime.strptime(job['job_date'], '%Y-%m-%d')
    job['job_skills'] = ast.literal_eval(job['job_skills'])

data_science_jobs


[{'job_title': 'Data Scientist',
  'job_skills': ['Python', 'SQL', 'Machine Learning'],
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Machine Learning Engineer',
  'job_skills': ['Python', 'TensorFlow', 'Deep Learning'],
  'job_date': datetime.datetime(2023, 5, 15, 0, 0)},
 {'job_title': 'Data Analyst',
  'job_skills': ['SQL', 'R', 'Tableau'],
  'job_date': datetime.datetime(2023, 5, 10, 0, 0)},
 {'job_title': 'Business Intelligence Developer',
  'job_skills': ['SQL', 'PowerBI', 'Data Warehousing'],
  'job_date': datetime.datetime(2023, 5, 8, 0, 0)},
 {'job_title': 'Data Engineer',
  'job_skills': ['Python', 'Spark', 'Hadoop'],
  'job_date': datetime.datetime(2023, 5, 18, 0, 0)},
 {'job_title': 'AI Specialist',
  'job_skills': ['Python', 'PyTorch', 'AI Ethics'],
  'job_date': datetime.datetime(2023, 5, 20, 0, 0)}]

In [ ]:
#exemplo de classes

class BaseSalary:
  def __init__(self, base_salary, bonus_rate=0.1, symbol="$"):
    self.base_salary = base_salary
    self.bonus_rate = bonus_rate
    self.symbol = symbol
    self.total_salary = base_salary * (1 + bonus_rate)
    self.bonus = self.total_salary - self.base_salary

  def __repr__(self):  #mostra se você colocar apenas o valor direto
    return f'{self.symbol}{self.base_salary:,.0f}'

  def show_salary(self):  #chamados de métodos de ação
    return f'{self.symbol}{self.total_salary:,.0f}'

  def show_bonus(self):  #outro método de ação
    return f'{self.symbol}{self.bonus:,.0f}'
  
salary = BaseSalary(100000)

salary

$100,000

In [10]:
salary.show_salary()

'$110,000'

In [ ]:
import numpy as np  #usado para manipular operações em geral

years_of_experience = np.array([1, 2, 3, 4, 5])

years_of_experience_plus_one = years_of_experience + 1
years_of_experience_plus_one

array([2, 3, 4, 5, 6])

In [4]:
years_of_experience_minus_one = years_of_experience - 1
years_of_experience_minus_one

array([0, 1, 2, 3, 4])

In [5]:
jobs_with_more_than_one_year_exp = years_of_experience[years_of_experience > 2]
jobs_with_more_than_one_year_exp

array([3, 4, 5])